metrics:
  regression:
  - r2
  - rmse
  - mae
  - medae
  - explained_variance
plots:
  feature_importances: false
  residual_hist: true
  residual_qq: true
  learning_curve: false
  pdp_2d: false
  pred_vs_actual: true
  prediction_error_hist: false
  pdp_1d: false
  residuals_vs_fitted: true
