tabular:
  algorithm: xgboost
  params:
    n_estimators: 500
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    reg_lambda: 1.0
    reg_alpha: 0.0
  baselines:
    linear:
      fit_intercept: true
    rf:
      n_estimators: 400
      max_depth: null
